name = "free"
main = "_worker.js"
compatibility_date = "2024-03-20"
compatibility_flags = [ "nodejs_compat" ]

# ✅ ဒီ line ကို ထည့်ပါ
keep_vars = true

[vars]
#UUID = ""

PROXYIP = "www.gco.gov.qa"
DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
